PRESETS = {
    "footsteps_cat": [
        ("preset_walk_wood", "Wooden floor footsteps, slow walking pace, hollow indoor reverb, single person"),
        ("preset_walk_concrete", "Concrete sidewalk footsteps, fast running, urban echo, hard soles"),
        ("preset_walk_gravel", "Gravel path footsteps, medium pace, crunchy stones underfoot, outdoor"),
        ("preset_walk_water", "Footsteps splashing through shallow water, slow wading, wet boots"),
        ("preset_walk_snow", "Snow crunch footsteps, cold winter, fresh powder, slow steady pace"),
        ("preset_walk_metal", "Metal grate footsteps, hollow industrial echo, factory catwalk"),
        ("preset_walk_leaves", "Dry autumn leaves footsteps, rustling forest path, crackling"),
        ("preset_walk_stone", "Heavy armored footsteps on stone tiles, medieval castle, knight, metallic clank"),
        ("preset_walk_dirt", "Dirt path footsteps, hiking trail, soft earth crunch, outdoor"),
        ("preset_walk_carpet", "Carpet footsteps, soft muffled steps, indoor home, quiet"),
        ("preset_walk_tiles", "Tile floor footsteps, kitchen, hard click of heels, echoing"),
        ("preset_walk_sand", "Sand footsteps, beach walking, soft grainy scrape, dune"),
        ("preset_walk_mud", "Mud footsteps, squelching wet ground, slow heavy boots"),
        ("preset_walk_grass", "Grass footsteps, walking through tall meadow field, gentle rustling"),
        ("preset_walk_ladder", "Climbing wooden ladder, hand and foot rungs, creaking wood"),
        ("preset_walk_swamp", "Swamp footsteps, splashing wet boots through bog, mud and reeds"),
    ],
    "impacts_cat": [
        ("preset_hit_punch", "Heavy punch impact, deep body thud, MMA fight, visceral, low-end"),
        ("preset_hit_sword_shield", "Sword clash on metal shield, sharp metallic ring, medieval combat"),
        ("preset_hit_wood_break", "Wooden crate breaking, splintering wood, heavy impact, debris"),
        ("preset_hit_glass_shatter", "Glass shattering on concrete floor, sharp crash, debris falling"),
        ("preset_hit_stone_fall", "Heavy stone block falling on dirt ground, dust cloud, dull thud"),
        ("preset_hit_anvil", "Hammer striking iron anvil, blacksmith forge, bright metal ring"),
        ("preset_hit_metal_clang", "Metal pipe striking concrete, harsh resonant clang, industrial"),
        ("preset_hit_punch_chest", "Punch impact on chest, dull body thud, brawl, visceral"),
        ("preset_hit_kick", "Heavy kick impact, body thud, martial arts, roundhouse"),
        ("preset_hit_axe_wood", "Axe chopping firewood, splinters flying, sharp blade strike"),
        ("preset_hit_meat", "Meat slapping on cutting board, butcher, wet thud, gore"),
        ("preset_hit_book_drop", "Heavy book dropping on wooden table, dull slam, library"),
        ("preset_hit_cardboard", "Cardboard box impact on floor, hollow dull thud"),
        ("preset_hit_water_splash", "Heavy water splash, body falling into pool, big splash"),
        ("preset_hit_bag_drop", "Heavy sandbag dropping on concrete floor, dense thud"),
        ("preset_hit_window_smash", "Window glass smashing, frame splintering, debris fall"),
    ],
    "movement_cat": [
        ("preset_move_whoosh", "Fast body movement whoosh through air, dynamic motion, wind"),
        ("preset_move_jump_wood", "Jump landing on wooden platform, soft thud, recovery footstep"),
        ("preset_move_jump_armor", "Heavy armored landing on stone, knight, metallic clank impact"),
        ("preset_move_dive", "Diving headfirst into water, splash and bubbles underwater"),
        ("preset_move_cloth", "Cloth fabric swish, fast ninja dodge, silk movement"),
        ("preset_move_run_fast", "Fast running whoosh through air, athletic motion, rapid"),
        ("preset_move_swing", "Sword swinging through air, fast slash, wind cut"),
        ("preset_move_punch_air", "Quick punch combo through air, boxing martial arts whooshes"),
        ("preset_move_kick_air", "High flying kick whoosh, martial arts swift movement"),
        ("preset_move_spin", "Body spinning fast, rotation whoosh, acrobatic motion"),
        ("preset_move_dash", "Quick sci-fi dash, instant teleport-like movement, energy"),
        ("preset_move_climb", "Climbing rope hand over hand, heavy effort grunts, strain"),
        ("preset_move_drag", "Body dragging across stone floor, scraping struggle, slow"),
        ("preset_move_crawl", "Slow crawling on stone floor, tense quiet movement, suspense"),
        ("preset_move_jump_metal", "Jump landing on metal platform, hollow clang resonance"),
        ("preset_move_roll", "Combat roll on ground, tactical military, quick recovery"),
        ("preset_move_slide", "Body sliding on smooth wooden floor, fast horizontal motion"),
    ],
    "ui_cat": [
        ("preset_ui_click", "Soft click button, modern minimal interface, subtle tone"),
        ("preset_ui_chime", "Magic spell unlock chime, fantasy game UI, sparkly bright tone"),
        ("preset_ui_error", "Error buzz, denied access, harsh negative descending tone"),
        ("preset_ui_coin", "Coin pickup, bright sparkle ding, retro arcade game"),
        ("preset_ui_ping", "Notification ping, soft friendly bell, modern app"),
        ("preset_ui_menu", "Menu opening swoosh, sci-fi interface, smooth transition"),
        ("preset_ui_achievement", "Achievement unlock fanfare, triumphant brass, RPG"),
        ("preset_ui_gameover", "Game over jingle, descending sad tones, defeat"),
        ("preset_ui_unlock", "Unlock chime, success golden tone, level complete"),
        ("preset_ui_purchase", "Purchase complete, cash register ding, retro shop"),
        ("preset_ui_levelup", "Level up fanfare, RPG progression, triumphant rising"),
        ("preset_ui_swipe", "Modern app swipe, smooth transition whoosh, mobile UI"),
        ("preset_ui_typing", "Mechanical keyboard typing, retro click clack rhythm"),
        ("preset_ui_loading", "Loading spinner sound, soft wait beep loop, idle"),
        ("preset_ui_message", "New message arrived, soft notification chime, friendly"),
        ("preset_ui_tab_switch", "Tab switching, modern UI subtle click, snappy"),
    ],
    "weapons_cat": [
        ("preset_weap_unsheath", "Sword unsheathing from leather scabbard, metallic high-pitched ring"),
        ("preset_weap_bow", "Bow drawing back tension, arrow nocked, leather creak"),
        ("preset_weap_arrow", "Arrow whoosh through air, fletching whistle, fast"),
        ("preset_weap_pistol", "Pistol gunshot, sharp 9mm crack with echo, dry"),
        ("preset_weap_machinegun", "Machine gun burst, rapid automatic fire, military"),
        ("preset_weap_fireball", "Magic fireball charging up, whoosh release, fantasy spell"),
        ("preset_weap_lightning", "Lightning bolt strike, electric crackle, magic energy"),
        ("preset_weap_shotgun", "Shotgun blast, double barrel boom, deep low end, pump action"),
        ("preset_weap_reload", "Gun magazine reloading, metallic click, military, sliding"),
        ("preset_weap_grenade", "Grenade explosion, military boom, debris and shrapnel"),
        ("preset_weap_dagger_throw", "Dagger throwing whistle through air, sharp blade flying"),
        ("preset_weap_axe_swing", "Battle axe heavy swing, medieval, wind cut, weighty"),
        ("preset_weap_crossbow", "Crossbow firing, mechanical click, bolt release, snap"),
        ("preset_weap_sniper", "Sniper rifle shot, distant booming echo, military"),
        ("preset_weap_grenade_bounce", "Grenade rolling on concrete, metallic hollow tumble"),
        ("preset_weap_silenced", "Silenced pistol shot, soft pop, tactical, suppressed"),
        ("preset_weap_rocket", "Rocket launcher firing, military missile launch, roar"),
    ],
    "ambience_cat": [
        ("preset_amb_forest_night", "Forest at night, crickets, distant owl, gentle wind"),
        ("preset_amb_rain_roof", "Heavy rain on tin roof, distant thunder, cozy"),
        ("preset_amb_spaceship", "Spaceship interior hum, sci-fi ambient drone"),
        ("preset_amb_tavern", "Medieval tavern, crowd chatter, fireplace crackle"),
        ("preset_amb_underwater", "Underwater submerged ambience, bubbles, deep low rumble"),
        ("preset_amb_city_night", "City rooftop at night, distant traffic, gentle wind"),
        ("preset_amb_cave", "Cave dripping water, echoing reverb, mysterious dark"),
        ("preset_amb_meadow", "Sunny meadow, birds chirping, gentle breeze"),
        ("preset_amb_desert", "Desert wind, sandstorm, vast emptiness"),
        ("preset_amb_haunted", "Haunted mansion, creaking wood, ghostly whispers"),
    ],
    "vehicles_cat": [
        ("preset_veh_car", "Sports car engine accelerating, asphalt road"),
        ("preset_veh_heli", "Helicopter rotor, hovering overhead"),
        ("preset_veh_train", "Train passing, rumbling tracks, doppler effect"),
        ("preset_veh_spaceship", "Spaceship engine starting, futuristic ignition"),
        ("preset_veh_motorcycle", "Motorcycle revving, throaty exhaust"),
        ("preset_veh_subway", "Subway train arriving at station, screeching brakes"),
        ("preset_veh_ship", "Wooden ship at sea, creaking hull, waves"),
    ],
    "nature_cat": [
        ("preset_nat_thunderstorm", "Thunderstorm, heavy rain, lightning crack, dramatic"),
        ("preset_nat_ocean", "Ocean waves crashing on shore, peaceful beach"),
        ("preset_nat_campfire", "Crackling campfire, warm cozy night"),
        ("preset_nat_stream", "Mountain stream, water flowing over rocks"),
        ("preset_nat_wind_trees", "Strong wind in trees, leaves rustling violently"),
        ("preset_nat_birds", "Birdsong morning chorus, dawn forest"),
        ("preset_nat_volcano", "Volcanic eruption, deep rumble, hot debris"),
        ("preset_nat_blizzard", "Blizzard wind, snow howling, freezing"),
    ],
    "music_cat": [
        ("preset_music_techhouse", "128 BPM tech house drum loop with crisp hi-hats"),
        ("preset_music_lofi", "Lo-fi hip hop beat, vinyl crackle, mellow Rhodes piano, 80 BPM"),
        ("preset_music_orchestra", "Cinematic orchestral build with timpani and brass swell"),
        ("preset_music_synthwave", "Synthwave arpeggio, retro 80s, gated reverb drums, 110 BPM"),
        ("preset_music_acoustic", "Acoustic guitar fingerpicking, warm and intimate"),
        ("preset_music_metal", "Heavy metal riff, distorted guitar, double bass drums, 160 BPM"),
        ("preset_music_trap", "Trap beat, 808 bass, hi-hat rolls, dark moody, 140 BPM"),
        ("preset_music_house", "Deep house bassline, smooth, 124 BPM"),
        ("preset_music_jazz", "Jazz trio improvisation, upright bass, brushed snare, ride cymbal"),
        ("preset_music_battle", "Epic battle music, war drums, choir, 140 BPM"),
        ("preset_music_ambient_pad", "Ambient pad, slow evolving textures, ethereal"),
        ("preset_music_reggae", "Reggae groove, off-beat skank guitar, laid-back drums, 95 BPM"),
    ],
    "cinematic_cat": [
        ("preset_cin_hit", "Cinematic trailer hit, deep boom impact"),
        ("preset_cin_drone", "Tension rising drone, suspenseful build-up"),
        ("preset_cin_riser", "Dramatic riser, pre-impact swell, climax"),
        ("preset_cin_dark_drone", "Mysterious atmospheric drone, dark ambient"),
        ("preset_cin_fanfare", "Heroic orchestral fanfare, triumphant brass"),
        ("preset_cin_chase", "Action movie chase music, fast strings, percussion"),
        ("preset_cin_sad_piano", "Sad emotional piano, slow tempo, melancholy"),
        ("preset_cin_glitch", "Glitch hit, modern trailer SFX, distorted impact"),
    ],
    "magic_cat": [
        ("preset_mag_heal", "Healing spell, gentle chime, magical sparkle, holy light"),
        ("preset_mag_curse", "Dark curse cast, evil whisper, ominous low frequencies"),
        ("preset_mag_teleport", "Teleport spell, swooshing portal energy, fantasy"),
        ("preset_mag_shield", "Magic shield activating, protective dome hum"),
        ("preset_mag_freeze", "Ice freezing spell, crystallizing crackles, cold magic"),
        ("preset_mag_summon", "Summoning ritual, mystical incantation, dark fantasy"),
        ("preset_mag_explosion", "Magic explosion, energy blast, wizardry"),
        ("preset_mag_charge", "Spell charging up, building magical energy"),
        ("preset_mag_potion", "Potion bubbling, alchemy lab, fizz and sparkle"),
        ("preset_mag_wand", "Magic wand cast, sparkly twinkle, fantasy"),
        ("preset_mag_portal", "Dimensional portal opening, otherworldly hum"),
        ("preset_mag_curse_break", "Curse breaking, redemption chord, light shines"),
        ("preset_mag_invisibility", "Invisibility cloaking, ghostly fade out"),
        ("preset_mag_levitate", "Levitation spell, floating airy whoosh"),
        ("preset_mag_transform", "Transformation magic, morphing energy, metamorphosis"),
        ("preset_mag_demon", "Demonic chant, low evil voices, ritual"),
        ("preset_mag_holy", "Holy choir, divine intervention, angelic voices"),
        ("preset_mag_drain", "Life drain spell, vampiric energy pull"),
    ],
    "scifi_cat": [
        ("preset_sci_laser", "Laser beam firing, sci-fi blaster, futuristic"),
        ("preset_sci_robot", "Robot servo movement, mechanical whir"),
        ("preset_sci_computer", "Computer interface beeping, retro sci-fi terminal"),
        ("preset_sci_alarm", "Alert klaxon, emergency siren, spaceship"),
        ("preset_sci_door", "Sci-fi door whoosh opening, pneumatic hiss"),
        ("preset_sci_forcefield", "Force field hum, energy barrier"),
        ("preset_sci_teleporter", "Teleporter beam, particle dematerialize"),
        ("preset_sci_engine_warp", "Warp drive engaging, light-speed buildup"),
        ("preset_sci_alien", "Alien voice, distorted otherworldly speech"),
        ("preset_sci_powerup", "Sci-fi power-up, charging energy, level up"),
        ("preset_sci_glitch", "Digital glitch, error static, broken signal"),
        ("preset_sci_drone", "Surveillance drone hovering, electronic hum"),
        ("preset_sci_cyborg", "Cyborg footsteps, metallic clanks, robotic"),
        ("preset_sci_radio", "Radio static, crackling transmission, interference"),
        ("preset_sci_servo", "Mechanical servo arm, robotic motion"),
        ("preset_sci_explosion", "Sci-fi energy explosion, plasma blast"),
        ("preset_sci_charge", "Energy weapon charging, building hum"),
        ("preset_sci_typing", "Holographic interface typing, digital tones"),
    ],
    "horror_cat": [
        ("preset_hor_scream", "Distant woman scream, horror, terrifying"),
        ("preset_hor_whisper", "Demonic whispers, evil low voices, supernatural"),
        ("preset_hor_laugh", "Creepy child laugh, horror, eerie"),
        ("preset_hor_creak", "Creaking door, abandoned house, suspense"),
        ("preset_hor_growl", "Monster growl, deep guttural, threatening"),
        ("preset_hor_heartbeat", "Anxious heartbeat, panic, building tension"),
        ("preset_hor_breathing", "Heavy panicked breathing, fear, claustrophobic"),
        ("preset_hor_static", "Demonic static, evil radio interference"),
        ("preset_hor_chains", "Rattling chains, dungeon, ghost"),
        ("preset_hor_jumpscare", "Jumpscare hit, sharp violins, sting impact"),
        ("preset_hor_bell", "Old church bell, ominous tolling, doom"),
        ("preset_hor_drone", "Horror ambient drone, dread, suspense"),
        ("preset_hor_squeal", "Pig squeal distorted, horror element, unsettling"),
        ("preset_hor_demonic", "Demonic chant, evil ritual, low voices"),
        ("preset_hor_skeleton", "Bone rattling, skeleton sounds, undead"),
        ("preset_hor_blood", "Blood dripping, gore atmosphere, dark"),
        ("preset_hor_ghost", "Ghostly wail, spectral moan, supernatural"),
        ("preset_hor_torture", "Distant torture chamber, screams, dungeon"),
    ],
    "animals_cat": [
        ("preset_anim_dog_bark", "Dog barking aggressively, large breed"),
        ("preset_anim_cat_meow", "Cat meowing softly, kitten"),
        ("preset_anim_lion", "Lion roaring, powerful, savanna"),
        ("preset_anim_wolf", "Wolf howling at moon, lonely"),
        ("preset_anim_horse", "Horse galloping on dirt path, strong"),
        ("preset_anim_bird_eagle", "Eagle screech, soaring high"),
        ("preset_anim_bear", "Bear growling, threatening, wild"),
        ("preset_anim_snake", "Snake hissing, threatening rattle"),
        ("preset_anim_dragon", "Dragon roar, fantasy, fire breath"),
        ("preset_anim_dinosaur", "T-Rex roar, dinosaur, jurassic"),
        ("preset_anim_owl", "Owl hooting, night forest"),
        ("preset_anim_pig", "Pig squealing, farm"),
        ("preset_anim_cow", "Cow mooing, peaceful pasture"),
        ("preset_anim_chicken", "Chicken clucking, farmyard"),
        ("preset_anim_frog", "Frog croaking, pond at night"),
        ("preset_anim_whale", "Whale song, deep ocean"),
        ("preset_anim_monster", "Monster roar, fantasy creature, beast"),
        ("preset_anim_zombie", "Zombie groan, undead, decayed"),
    ],
    "voices_cat": [
        ("preset_voi_crowd_cheer", "Stadium crowd cheering, sports victory"),
        ("preset_voi_crowd_chatter", "Restaurant crowd chatter, ambient murmur"),
        ("preset_voi_crowd_panic", "Panicked crowd running, screams"),
        ("preset_voi_applause", "Audience applause, theatre clapping"),
        ("preset_voi_boo", "Crowd booing, disappointment"),
        ("preset_voi_laughing", "Group laughter, comedy show"),
        ("preset_voi_baby_cry", "Baby crying, infant"),
        ("preset_voi_market", "Open market chatter, vendors calling"),
        ("preset_voi_school", "School playground children, recess"),
        ("preset_voi_protest", "Protest chants, megaphone, crowd"),
        ("preset_voi_bar", "Bar nightlife chatter, drinks clinking"),
        ("preset_voi_office", "Office ambient, typing, phones ringing"),
        ("preset_voi_concert", "Concert crowd cheering, festival"),
        ("preset_voi_wedding", "Wedding ceremony applause, joyful"),
        ("preset_voi_gym", "Gym ambient, weights clanking, grunts"),
        ("preset_voi_classroom", "Classroom learning, teacher voice"),
        ("preset_voi_subway", "Subway station crowd, footsteps"),
        ("preset_voi_courtroom", "Courtroom murmur, gavel"),
    ],
}
